# 应用服务 WEB 访问端口
server:
  port: 8080

pay:
  # 微信支付
  wechat:
    app-id: wxxxxx
    mch-id: xxxx
    mch-key: xxxxx
    key-path: classpath:cert/apiclient_cert.p12
    notify-url: http://xxxx/wx/notify/pay
    refund-notify-url: http://xxxx/wx/notify/refund

  # 支付宝支付
  alipay:
    app-id: 2021000123456789
    private-key:
    public-key:
    server-url: https://openapi.alipay.com/gateway.do
    notify-url: https://your-domain.com/alipay/notify
    return-url: https://your-domain.com/alipay/return

  # 京东支付
  jdpay:
    mch-id:
    des-key:
    md5-key:
    sha-key:
    user-id:
    pay-url: https://wepay.jd.com/degrade
    notify-url:
    return-url:
    rsa-public-key:
    rsa-private-key:

  # 银联支付
  ums:
    mch-id:
    tid:
    msg-id:
    notify-url:
    return-url:



