# 应用服务 WEB 访问端口
server:
  port: 8080

pay:
  # 微信支付
  wechat:
    app-id: wxxxxx
    mch-id: xxxx
    mch-key: xxxxx
    key-path: classpath:cert/apiclient_cert.p12
    notify-url: http://xxxx/wx/notify/pay
    refund-notify-url: http://xxxx/wx/notify/refund

  # 支付宝支付
  alipay:
    app-id: xxxxxxxxxxxxxxxx
    private-key:
    public-key:
    server-url: https://openapi.alipay.com/gateway.do
    notify-url: https://your-domain.com/alipay/notify
    return-url: https://your-domain.com/alipay/return

  # 京东原生支付
  jdpay:
    mch-id:
    des-key:
    md5-key:
    sha-key:
    user-id:
    pay-url: https://wepay.jd.com/degrade
    notify-url:
    return-url:
    rsa-public-key:
    rsa-private-key:

  # 银联聚合支付
  ums:
    mch-id:
    tid:
    msg-id:
    notify-url:
    return-url:
    sign-key:
    pay-url: https://qr.chinaums.com/netpay-route-server/api/
    msg-src:

  # 招商聚合支付
  cmb:
    mch-id: xxxxxxxxxxxxxxx
    app-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    secret: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    notify-url: http://xxxxx/cmb/notify/pay
    return-url: http://xxxxx/cmb/notify/refund
    cmb-public-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    mch-private-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



